// import about from '/img/media/about.jpg';

export const Images = {
  about: '/img/media/about.jpg',
  actu: '/img/media/actu.png',
  bill_chaser_banner: '/img/media/bill_chaser_banner.jpg',
  bill_charser: '/img/media/bill_charser.png',
  builder: '/img/media/builder.jpg',
  cfmeu: '/img/media/cfmeu.png',
  clock: '/img/media/clock.svg',
  contact: '/img/media/contact.jpg',
  enablement_partners: '/img/media/enablement_partners.png',
  help: '/img/media/help.jpg',
  home: '/img/media/home.jpg',
  license: '/img/media/license.png',
  logos_about: '/img/media/logos_about.png',
  logos_sm: '/img/media/logos_sm.png',
  logos: '/img/media/logos.png',
  man: '/img/media/man.jpg',
  maze: '/img/media/maze.png',
  medicare: '/img/media/medicare.png',
  nbn_packs: '/img/media/nbn_packs.png',
  optus: '/img/media/optus.png',
  oval_cars: '/img/media/oval_cars.png',
  oval_electricity: '/img/media/oval_electricity.png',
  oval_gas: '/img/media/oval_gas.png',
  oval_insurance: '/img/media/oval_insurance.png',
  oval_member_discounts: '/img/media/oval_member_discounts.png',
  oval_upoint_cards: '/img/media/oval_upoint_cards.png',
  partnerships: '/img/media/partnerships.jpg',
  passport: '/img/media/passport.png',
  people_money: '/img/media/people_money.png',
  plans: '/img/media/plans.png',
  sim_alone: '/img/media/sim_alone.png',
  sim_login: '/img/media/sim_login.png',
  sim_micro_standard: '/img/media/sim_micro_standard.png',
  sim_nano: '/img/media/sim_nano.png',
  sim1: '/img/media/sim1.png',
  sim3: '/img/media/sim3.png',
  telcoinabox: '/img/media/telcoinabox.png',
  telstra: '/img/media/telstra.png',
  union_logos: '/img/media/union_logos.png',
  upoint_card: '/img/media/upoint_card.png',
  upoint_cards: '/img/media/upoint_cards.jpg',
  upoint_partners: '/img/media/upoint_partners.jpg',
  upoint: '/img/media/upoint.png',
  visa: '/img/media/visa.png',
  wholesale: '/img/media/wholesale.png',
  woman: '/img/media/woman.jpg'
};

export const Icons = {
  australian_support: '/img/icons/australian_support.svg',
  cart: '/img/icons/cart.svg',
  check: '/img/icons/cart.svg',
  customer_existing: '/img/icons/customer_existing.svg',
  customer_new: '/img/icons/customer_new.svg',
  customer_replace: '/img/icons/customer_replace.svg',
  cutting_out: '/img/icons/cutting_out.svg',
  dropdown: '/img/icons/dropdown.svg',
  facebook: '/img/icons/facebook.svg',
  fuel: '/img/icons/fuel.svg',
  giving_back: '/img/icons/giving_back.svg',
  instagram: '/img/icons/instagram.svg',
  login: '/img/icons/login.svg',
  logo_footer: '/img/icons/logo_footer.svg',
  logo: '/img/icons/logo.svg',
  mobile_transfer: '/img/icons/mobile_transfer.svg',
  mobile: '/img/icons/mobile.svg',
  mobile1: '/img/icons/mobile1.svg',
  money_light: '/img/icons/money_light.svg',
  plus: '/img/icons/plus.svg',
  service_new: '/img/icons/service_new.svg',
  sim1: '/img/icons/sim1.svg',
  sim2: '/img/icons/sim2.svg',
  sim3: '/img/icons/sim3.svg',
  sim4: '/img/icons/sim4.svg',
  twitter: '/img/icons/twitter.svg',
  user: '/img/icons/user.svg',
  wifi: '/img/icons/wifi.svg'
};

export const Docs = {
  UPoint_CIS_MAX_Mobile_May_2018: '/docs/UPoint_CIS_MAX_Mobile_May_2018.pdf',
  UPoint_CIS_STANDARD_May_2018: '/docs/UPoint_CIS_STANDARD_May_2018.pdf',
  UPoint_CIS_SUPER_Mobile_May_2018: '/docs/UPoint_CIS_SUPER_Mobile_May_2018.pdf',
  UPoint_International_Call_Rates_May_2018: '/docs/UPoint_International_Call_Rates_May_2018.pdf',
  UPoint_Invoice_Explainer: '/docs/UPoint_Invoice_Explainer.pdf',
  UPoint_Invoice: '/docs/UPoint_Invoice.pdf',
  UPoint_Product_Sheet_Mobile_May_2018: '/docs/UPoint_Product_Sheet_Mobile_May_2018.pdf'
};
